### ISSUE TITLE
Person.equals a bit odd

### ISSUE THREAD

**Issue by salk31** [UrszulaNeuman/DlsSummerSchoolScheduler#6]
It uses the identity operator for id but unless the id is System.interned this might not work.

Could ensure is interned or ensure no duplicate instances for the "same" person so then could just reply on personA == personB   worth looking at Object.equals implementation

Often good to avoid re-implementing equals because that implies you should re-implement Object.hasCode else HashMap etc will behave in odd ways.

**Comment by UrszulaNeuman** [comment]
I used person id (which should be unique) in comparisons instead.
