### ISSUE TITLE
Hard to see how hard it worked etc

### ISSUE THREAD

**Issue by salk31** [UrszulaNeuman/DlsSummerSchoolScheduler#7]
Maybe use the benchmark stuff?

https://docs.jboss.org/drools/release/5.4.0.Beta2/drools-planner-docs/html/ch10.html

**Comment by UrszulaNeuman** [comment]
When logging  is on each step of the process is visible.
More about logging:
http://docs.jboss.org/optaplanner/release/6.3.0.Final/optaplanner-docs/html_single/index.html#logging
